# Generated by Django 5.0.3 on 2024-08-21 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="会话名字", max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="创建该会话的用户id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(help_text="消息内容")),
                ("role", models.CharField(help_text="角色", max_length=100)),
                ("model", models.CharField(help_text="模型", max_length=100)),
                ("date_time", models.CharField(help_text="时间", max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="用户id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        help_text="会话id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat.room",
                    ),
                ),
            ],
        ),
    ]
