# Generated by Django 5.0.3 on 2024-08-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="active",
            field=models.BooleanField(default=False, help_text="记录当前会话"),
        ),
    ]
