# Generated by Django 5.0.3 on 2024-08-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_room_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="checked",
            field=models.BooleanField(default=False, help_text="是否选中"),
        ),
    ]
