# Generated by Django 5.0.3 on 2024-08-23 08:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_room_checked"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="create_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
