# Generated by Django 5.0.3 on 2024-08-29 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_room_create_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="active",
        ),
    ]
