# Generated by Django 5.0.3 on 2024-08-29 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_remove_room_active"),
        ("user", "0002_profile_default_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="default_room",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chat.room",
            ),
        ),
    ]
